
CREATE TABLE LOCATION(
    CODE VARCHAR(10) primary key,
    NAME VARCHAR(50),
    COUNTRY VARCHAR(50),
    CITY VARCHAR(50)
);

CREATE TABLE TRANSPORTATION(
    ID BIGINT primary key,
    TYPE VARCHAR(10),
    ORIGIN_LOCATION_CODE VARCHAR(10),
    DESTINATION_LOCATION_CODE VARCHAR(10),
    FOREIGN KEY (ORIGIN_LOCATION_CODE) REFERENCES LOCATION(CODE),
    FOREIGN KEY (DESTINATION_LOCATION_CODE) REFERENCES LOCATION(CODE),
    CONSTRAINT uidx_transportation_01 UNIQUE (ORIGIN_LOCATION_CODE, DESTINATION_LOCATION_CODE, TYPE)
);

CREATE INDEX IDX_TRANSPORTATION_01 ON TRANSPORTATION(DESTINATION_LOCATION_CODE, TYPE);
CREATE INDEX IDX_TRANSPORTATION_02 ON TRANSPORTATION(ORIGIN_LOCATION_CODE, TYPE);

CREATE TABLE TRANSPORTATION_SCHEDULE(
    ID BIGINT,
    TRANSPORTATION_ID BIGINT,
    OPERATING_DAY BIGINT,
    FOREIGN KEY (TRANSPORTATION_ID) REFERENCES TRANSPORTATION(ID),
    CONSTRAINT uidx_transportatıon_schedule_01 UNIQUE (TRANSPORTATION_ID, OPERATING_DAY)
);

CREATE INDEX IDX_TRANSPORTATION_SCHEDULE_01 ON TRANSPORTATION_SCHEDULE(TRANSPORTATION_ID);

CREATE SEQUENCE SEQ_TRANSPORTATION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRANSPORTATION_SCHEDULE START WITH 1 INCREMENT BY 1;


